name: card_scan
description: "A Flutter plugin for card scanning."
version: 1.0.1
homepage: https://github.com/jyahann/card_scan

environment:
  sdk: ^3.9.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jyahann.card_scan
        pluginClass: CardScanPlugin
      ios:
        pluginClass: CardScanPlugin
